#!/bin/bash

NODE_ENV=production TUTORIAL_EDIT=1 npm --silent run -- gulp tutorial:import --root /js/javascript-tutorial
NODE_ENV=production TUTORIAL_EDIT=1 npm --silent run -- gulp edit --root /js/javascript-tutorial

