#!/bin/bash
sudo rm /var/log/nginx/*
npm --silent run gulp -- config:nginx --prefix /opt/local/etc/nginx --env development --root /js/javascript-nodejs
sudo port unload nginx
sudo pkill -9 nginx
sudo port load nginx
