#!/bin/bash

# Delete all
curl -XDELETE 'http://localhost:9200/*'

# Partial delete
# curl -XDELETE 'http://localhost:9200/js'
curl -XPUT 'http://localhost:9200/js' -d @db-js.json

# get indexed docs count
#curl -X GET 'localhost:9200/js/articles/_count?pretty'

# check
# curl 'http://localhost:9200/js/articles/_search?pretty=true' -d '{"query": {"query_string": {"query": "title:события"}}, "fields":["_id"]}'
